/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.wcrm.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.wcrm.core.entity.Customer.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed Jan 13 10:47:31 CST 2021")
public class Customer_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Customer,String> address;
    public static volatile SingularAttribute<Customer,String> cellphone;
    public static volatile SingularAttribute<Customer,String> city;
    public static volatile SingularAttribute<Customer,String> createuser;
    public static volatile SingularAttribute<Customer,String> customername;
    public static volatile SingularAttribute<Customer,String> dealstatus;
    public static volatile SingularAttribute<Customer,String> detailaddress;
    public static volatile SingularAttribute<Customer,String> follow;
    public static volatile SingularAttribute<Customer,String> id;
    public static volatile SingularAttribute<Customer,String> industry;
    public static volatile SingularAttribute<Customer,String> islock;
    public static volatile SingularAttribute<Customer,String> lat;
    public static volatile SingularAttribute<Customer,String> level;
    public static volatile SingularAttribute<Customer,String> lng;
    public static volatile SingularAttribute<Customer,String> location;
    public static volatile SingularAttribute<Customer,Date> nexttime;
    public static volatile SingularAttribute<Customer,String> owneruser;
    public static volatile SingularAttribute<Customer,String> pinyin;
    public static volatile SingularAttribute<Customer,String> pinyinInitial;
    public static volatile SingularAttribute<Customer,String> province;
    public static volatile ListAttribute<Customer,String> readerUserIds;
    public static volatile SingularAttribute<Customer,String> remark;
    public static volatile SingularAttribute<Customer,String> source;
    public static volatile SingularAttribute<Customer,String> telephone;
    public static volatile SingularAttribute<Customer,String> website;
    public static volatile ListAttribute<Customer,String> writerUserIds;
}
