/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.wcrm.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.wcrm.core.entity.Leads.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed Jan 13 10:47:31 CST 2021")
public class Leads_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Leads,String> address;
    public static volatile SingularAttribute<Leads,String> cellphone;
    public static volatile SingularAttribute<Leads,String> content;
    public static volatile SingularAttribute<Leads,String> createuser;
    public static volatile SingularAttribute<Leads,String> customerid;
    public static volatile SingularAttribute<Leads,String> follow;
    public static volatile SingularAttribute<Leads,Date> gjTime;
    public static volatile SingularAttribute<Leads,String> id;
    public static volatile SingularAttribute<Leads,String> industry;
    public static volatile SingularAttribute<Leads,String> istransform;
    public static volatile SingularAttribute<Leads,String> level;
    public static volatile SingularAttribute<Leads,String> name;
    public static volatile SingularAttribute<Leads,Date> nexttime;
    public static volatile SingularAttribute<Leads,String> owneruser;
    public static volatile SingularAttribute<Leads,String> pinyin;
    public static volatile SingularAttribute<Leads,String> pinyinInitial;
    public static volatile SingularAttribute<Leads,String> province;
    public static volatile ListAttribute<Leads,String> readerUserIds;
    public static volatile SingularAttribute<Leads,String> remark;
    public static volatile SingularAttribute<Leads,String> source;
    public static volatile SingularAttribute<Leads,String> telephone;
    public static volatile ListAttribute<Leads,String> writerUserIds;
}
