/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.wcrm.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.wcrm.core.entity.OpportunityType.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed Jan 13 10:47:31 CST 2021")
public class OpportunityType_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OpportunityType,String> createuser;
    public static volatile SingularAttribute<OpportunityType,String> id;
    public static volatile SingularAttribute<OpportunityType,String> opportunitytypename;
    public static volatile SingularAttribute<OpportunityType,String> pinyin;
    public static volatile SingularAttribute<OpportunityType,String> pinyinInitial;
    public static volatile ListAttribute<OpportunityType,String> readUnitList;
    public static volatile SingularAttribute<OpportunityType,String> typeid;
}
