/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.wcrm.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.wcrm.core.entity.WCrmConfig.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed Jan 13 10:47:31 CST 2021")
public class WCrmConfig_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<WCrmConfig,String> configCode;
    public static volatile SingularAttribute<WCrmConfig,String> configName;
    public static volatile SingularAttribute<WCrmConfig,String> configValue;
    public static volatile SingularAttribute<WCrmConfig,String> description;
    public static volatile SingularAttribute<WCrmConfig,String> id;
    public static volatile SingularAttribute<WCrmConfig,Boolean> isMultiple;
    public static volatile SingularAttribute<WCrmConfig,Integer> orderNumber;
    public static volatile SingularAttribute<WCrmConfig,String> selectContent;
    public static volatile SingularAttribute<WCrmConfig,String> valueType;
}
