/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.wcrm.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.wcrm.core.entity.WTest.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed Jan 13 10:47:31 CST 2021")
public class WTest_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<WTest,String> id;
    public static volatile SingularAttribute<WTest,String> remark;
    public static volatile SingularAttribute<WTest,String> subject;
}
